name: security-action
on:
  push:
    branches: [main]

jobs:
  build:
    name: build maven
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1 
      with:
        java-version: 1.8
    - name: build maven
      run: |
        mvn clean package install
        pwd
        ls -l  
    - name: salvando artefato
      uses: actions/upload-artifact@v4
      with:
          name: verademo.war
          path: target/verademo.war

  veracode-sca:
    runs-on: ubuntu-latest
    name: veracode sca
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: veracode sca scan
        env: 
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --update-advisor --uri-as-name --ref ${{ github.ref_name }}

  veracode-container-iac-secrets-scan:
    runs-on: ubuntu-latest
    name: Veracode Container/IaC/Secrets scan
    needs: [ build ]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Veracode Container/IaC/Secrets action step
        uses: veracode/container_iac_secrets_scanning@v1.0.3
        with:
          vid: '${{ secrets.APIID }}'
          vkey: '${{ secrets.APIKEY }}'
          command: "scan" 
          type: "directory"
          source: "./"
          format: "table"
          debug: false
          fail_build: false

  veracode-sast-sandbox-scan:
    name: veracode sandbox branch scan
    runs-on: ubuntu-latest
    needs: [ build, veracode-sca, veracode-container-iac-secrets-scan ]
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
        
      - uses: actions/checkout@v3
      - name: get archive
        uses: actions/download-artifact@v4 
        with:
          name: verademo.war
          path: .

      - name: veracode sandbox branch scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'verademopractice-java-web'
          createprofile: true
          filepath: 'verademo.war'
          vid: '${{ secrets.APIID }}'
          vkey: '${{ secrets.APIKEY }}'
          createsandbox: 'true'
          sandboxname: "${{ github.ref }}"
          version: "${{ github.run_id }}"
          scantimeout: 0

  veracode-sast-policy-scan:
    name: veracode policy scan
    runs-on: ubuntu-latest
    needs: [ build, veracode-sca, veracode-container-iac-secrets-scan, veracode-sast-sandbox-scan ]
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
        
      - name: get archive
        uses: actions/download-artifact@v4 
        with:
          name: verademo.war
          path: .

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'verademopractice-java-web'
          createprofile: true
          filepath: 'verademo.war'
          vid: '${{ secrets.APIID }}'
          vkey: '${{ secrets.APIKEY }}'
          version: "${{ github.run_id }}"
          scantimeout: 0

  veracode-sast-pipeline-scan:
    runs-on: ubuntu-latest
    needs: [ build, veracode-sca, veracode-container-iac-secrets-scan, veracode-sast-sandbox-scan ]
    name: veracode sast pipeline scan

    steps:
      - name: get archive
        uses: actions/download-artifact@v4 
        with:
          name: verademo.war
          path: .

      - name: pipeline-scan action step
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.16
        with:
          vid: ${{ secrets.APIID }}
          vkey: ${{ secrets.APIKEY }}
          file: "verademo.war"
          veracode_policy_name: "Veracode Recommended Medium"
          fail_build: "true"
